export const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    REMOVE_ITEM: 'REMOVE_ITEM',
    INCREASE: 'INCREASE',
    DECREASE: 'DECREASE',
    CLEAR_ALL: 'CLEAR_ALL',
    CLEAR_CART: 'CLEAR_CART',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS'
}